### ISSUE TITLE
Crash using Mosquitto, local, passwordless

### ISSUE THREAD

**Issue by eode** [ClassicDIY/Classic#15]
Awesome work on this app.

Severity: minor (easy workaround)

Environment:
* Local network
* Raspberry Pi
* mosquitto **(no username and password required)**, sharing data with your app and HomeAssistant.

Current behavior:
Using no username/password causes Android app to crash when clicking on the classic's name in the swipe-out list on the left.  

Expected behavior:
Using no username/password doesn't cause a crash when clicking on classic's name in the swipe-out list on the left.

Workaround:
Use a junk username/password.

**Comment by graham22** [comment]
Version 3.0.4 ready for testing in [preRelease](https://github.com/ClassicDIY/Classic/releases/tag/3.0.4)

**Comment by eode** [comment]
Might need version bump, if that matters.  I had to uninstall before installing.

This release fixes the issue, though.  Can confirm.
